config/routes.rb
Rails.application.routes.draw do
  resources :players

  resources :questions

  resources :quizzes

  devise_for :users
   root 'welcome#index'
      get 'start_quiz' => 'players#start_quiz', as: :start_quiz
      
      get 'dash_board' => 'players#dash_board', as: :dash_board
      
     get  'record_progress' => 'players#record_progress', as: :record_progress
     
     post  'record_progress' => 'players#record_progress'
      

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :quiz
  validates_presence_of :question, :option_a, :option_b
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
    session[:created_quiz_question_number] += 1
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.quiz_id = session[:created_quiz]
    @question.question_number = session[:created_quiz_question_number]

    respond_to do |format|
#      if @question.answer !=@question.option_a and @question.answer !=@question.option_b and @question.answer !=@question.option_c and @question.answer !=@question.option_d
#          format.html { render :new }
        
      if @question.save
        #format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.html { redirect_to new_question_path, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:quiz_id, :question_number, :question, :option_a, :option_b, :option_c, :option_d, :answer)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <!-- <div class="field">
    <%= f.label :quiz_id %><br>
    <%= f.text_field :quiz_id %>
  </div>
  <div class="field">
    <%= f.label :question_number %><br>
    <%= f.number_field :question_number %>
  </div>-->
  <h1>Question <%=session[:created_quiz_question_number]%></h1>
  
  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :option_a %><br>
    <%= f.text_field :option_a %>
  </div>
  <div class="field">
    <%= f.label :option_b %><br>
    <%= f.text_field :option_b %>
  </div>
  <div class="field">
    <%= f.label :option_c %><br>
    <%= f.text_field :option_c %>
  </div>
  <div class="field">
    <%= f.label :option_d %><br>
    <%= f.text_field :option_d %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    
    
    A.<%=f.radio_button :answer, "option_a" %>
    B.<%=f.radio_button :answer, "option_b" %>
    C.<%=f.radio_button :answer, "option_c" %>
    D.<%=f.radio_button :answer, "option_d" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <thead>
    <tr>
      <th>Quiz</th>
      <th>Question number</th>
      <th>Question</th>
      <th>Option a</th>
      <th>Option b</th>
      <th>Option c</th>
      <th>Option d</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.quiz %></td>
        <td><%= question.question_number %></td>
        <td><%= question.question %></td>
        <td><%= question.option_a %></td>
        <td><%= question.option_b %></td>
        <td><%= question.option_c %></td>
        <td><%= question.option_d %></td>
        <td><%= question.answer %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Done', root_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quiz:</strong>
  <%= @question.quiz %>
</p>

<p>
  <strong>Question number:</strong>
  <%= @question.question_number %>
</p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>

<p>
  <strong>Option a:</strong>
  <%= @question.option_a %>
</p>

<p>
  <strong>Option b:</strong>
  <%= @question.option_b %>
</p>

<p>
  <strong>Option c:</strong>
  <%= @question.option_c %>
</p>

<p>
  <strong>Option d:</strong>
  <%= @question.option_d %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @question.answer %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>