config/routes.rb
Rails.application.routes.draw do
  resources :players

  resources :questions

  resources :quizzes

  devise_for :users
   root 'welcome#index'
      get 'start_quiz' => 'players#start_quiz', as: :start_quiz
      
      get 'dash_board' => 'players#dash_board', as: :dash_board
      
     get  'record_progress' => 'players#record_progress', as: :record_progress
     
     post  'record_progress' => 'players#record_progress'
      

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:[:new, :create]#add for play as well later

  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
    session[:current_quiz] = @quiz.id
  end

  # GET /quizzes/new
  def new
    @users = User.all
    @logged_user = current_user
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)
    @quiz.user_id = current_user.id
    
    respond_to do |format|
      if @quiz.save
        session[:created_quiz] = @quiz.id
        session[:created_quiz_question_number] = 0
        format.html { redirect_to new_question_path, notice: 'Quiz was successfully created.' }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:title, :user_id, :tag)
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.erb
<%= form_for(@quiz) do |f| %>
  <% if @quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% @quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
   <!-- <%= f.label :user_id %><br>
    <%= f.select :user_id, options_for_select(@users.map{|s|[s.email, s.id]})%>-->
  </div>
  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Editing quiz</h1>

<%= render 'form' %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<h1 style="text-align: center">Listing quizzes</h1>

<table>
  <thead>
    <tr>
      <th>Title(tag)</th>
      <th style="text-align: right">Tag</th>
      <th style="text-align: right">Author</th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><div id="navigation">
	    <ul><li><%= link_to quiz.title, quiz%></a></li></ul></td></div>
        <td style="text-align: right">
	    <ul><li><a ><%=quiz.tag %></a></li></ul></td>
        <td style="text-align: right">
	    <ul><li><a ><%=quiz.user.email %></a></li></ul></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Quiz', new_quiz_path %>-->

app/views/quizzes/new.html.erb
<h1>New quiz</h1>

<%= render 'form' %>

<%= link_to 'Back', quizzes_path %>

app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @quiz.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @quiz.user.email %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @quiz.tag %>
  <%session[:current] = @quiz.id%>
</p>

<%= link_to 'Play', "/start_quiz" %>